if(sessionStorage.getItem("canteenAdmin")!=="yes")location.href="admin-login.html";
let products=getProducts();document.getElementById("adminCollege").textContent=SITE_SETTINGS.collegeName;document.getElementById("collegeInput").value=SITE_SETTINGS.collegeName;document.getElementById("logoInput").value=SITE_SETTINGS.logo;
function render(){products=getProducts();document.getElementById("productStat").textContent=products.length;document.getElementById("availableStat").textContent=products.filter(p=>p.available).length;document.getElementById("orderStat").textContent=getOrders().length;document.getElementById("productTable").innerHTML=`<div class="table-wrap"><table><thead><tr><th>Item</th><th>Category</th><th>Price</th><th>Status</th><th>Action</th></tr></thead><tbody>${products.map(p=>`<tr><td><b>${p.name}</b></td><td>${p.category}</td><td>₹${p.price}</td><td><span class="pill ${p.available?"on":"off"}">${p.available?"Available":"Hidden"}</span></td><td><button onclick="editProduct('${p.id}')">Edit</button> <button class="danger" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join("")}</tbody></table></div>`;document.getElementById("adminOrders").innerHTML=getOrders().length?getOrders().map(o=>`<div class="admin-order"><b>${o.id}</b><span>${o.userName} • ${o.userPhone}</span><span>${o.items.map(i=>i.name+" × "+i.qty).join(", ")}</span><b>₹${o.total}</b><select onchange="setStatus('${o.id}',this.value)"><option ${o.status==="Pending"?"selected":""}>Pending</option><option ${o.status==="Preparing"?"selected":""}>Preparing</option><option ${o.status==="Ready"?"selected":""}>Ready</option><option ${o.status==="Completed"?"selected":""}>Completed</option></select></div>`).join(""):"<p class='muted'>No local orders yet.</p>";}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;editId.value=p.id;pName.value=p.name;pCategory.value=p.category;pPrice.value=p.price;pImage.value=p.imageUrl;pDesc.value=p.description;pPrep.value=p.prepTime;pAvailable.checked=p.available;cancelEdit.classList.remove("hidden");scrollTo({top:0,behavior:"smooth"});}
function deleteProduct(id){if(!confirm("Delete this product?"))return;saveProducts(getProducts().filter(p=>p.id!==id));render();}
productForm.onsubmit=e=>{e.preventDefault();let arr=getProducts(),id=editId.value||"p"+Date.now(),obj={id,name:pName.value.trim(),category:pCategory.value.trim(),price:Number(pPrice.value),imageUrl:pImage.value.trim()||"https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80",description:pDesc.value.trim(),prepTime:pPrep.value.trim()||"10 min",available:pAvailable.checked};const i=arr.findIndex(p=>p.id===id);if(i>=0)arr[i]=obj;else arr.push(obj);saveProducts(arr);productForm.reset();pAvailable.checked=true;editId.value="";cancelEdit.classList.add("hidden");render();};
cancelEdit.onclick=()=>{productForm.reset();pAvailable.checked=true;editId.value="";cancelEdit.classList.add("hidden");};
resetProducts.onclick=()=>{if(confirm("Reset menu to default products?")){saveProducts(DEFAULT_PRODUCTS);render();}};
settingsForm.onsubmit=e=>{e.preventDefault();localStorage.setItem("canteenSettings",JSON.stringify({collegeName:collegeInput.value.trim()||SITE_SETTINGS_DEFAULT.collegeName,logo:logoInput.value.trim()||"🍽️"}));settingsMsg.textContent="Branding saved in this browser.";};
function setStatus(id,status){let o=getOrders();let x=o.find(x=>x.id===id);if(x){x.status=status;saveOrders(o);render();}}
logout.onclick=()=>{sessionStorage.removeItem("canteenAdmin");location.href="admin-login.html"};render();
